server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: swiggy-service
          uri: lb://swiggy-service
          predicates:
            - Path=/swiggy/**
          filters:
            - AuthFilter

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**
          filters:
            - AuthFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

